# values.yaml for Alertmanager (Helm chart)
replicaCount: 2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistentVolume:
  enabled: true
  size: 5Gi
  storageClass: "standard"

config:
  global:
    resolve_timeout: 5m
    smtp_smarthost: "smtp.example.com:587" # TODO: store in secret
    smtp_from: "alerts@example.com"

  route:
    receiver: "ops-email"
    group_by: ["alertname", "cluster", "service"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 3h
    routes:
      - match:
          severity: critical
        receiver: "pagerduty"
        continue: true
      - match_re:
          team: infra|platform
        receiver: "ops-email"

  receivers:
    - name: "ops-email"
      email_configs:
        - to: "ops-team@example.com"
          send_resolved: true

    - name: "pagerduty"
      pagerduty_configs:
        - routing_key: "YOUR_PD_INTEGRATION_KEY" # TODO: store in secret
          send_resolved: true
  templates:
    - "/etc/alertmanager/templates/email.tmpl"
    - "/etc/alertmanager/templates/slack.tmpl"
